// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anzquikanbnbvjzgpbbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuenF1aWthbmJuYnZqemdwYmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjM5MTUsImV4cCI6MjA2MDE5OTkxNX0.3IAK8oinl1-0kHqvYkFEaGs1Q4DdqFxgpA0Fox40HJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);